name: Ubuntu 20.04 CI (GCC 9)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake  -DCMAKE_INSTALL_PREFIX:PATH=destination ..  &&
          cmake --build .   &&
          ctest -j --output-on-failure  &&
          make install  &&
          echo -e '#include <cbitset/bitset.h>\nint main(int argc,char**argv) {bitset_t * b = bitset_create(); bitset_set(b,10); bitset_get(b,10); bitset_free(b); }' > tmp.c && cc  -Idestination/include  -Ldestination/lib -std=c11 -Wl,-rpath,destination/lib -o linkandrun tmp.c -lcbitset && ./linkandrun 
