#
#COPYRIGHT 2012 Pluribus Networks Inc.
#
#All rights reserved. This copyright notice is Copyright Management
#Information under 17 USC 1202 and is included to protect this work and
#deter copyright infringement.  Removal or alteration of this Copyright
#Management Information without the express written permission from
#Pluribus Networks Inc is prohibited, and any such unauthorized removal
#or alteration will be a violation of federal law.
#

TOP		= ../..
PACKAGE		= pn-nvos
INCS		=
LIBS		= -lcurses
C_SRCS		= nvmore.c
BINARY		= nvmore

include $(TOP)/Makedefs
